### ISSUE TITLE
Telnet console access not working anymore

### ISSUE THREAD

**Issue by utobi** [swookiee/com.swookiee.runtime#11]
Starting the runtime does not start the telnet console anymore.

**Comment by larsp** [comment]
Not sure if this has always been enforced, but from the equinox documentation:

> The property osgi.console specifies the port on which the console should listen for telnet connections. Instead of specifying this property, you can start the framework with the -console <port> option. If you do not specify the port in either of these ways, the console will not listen for telnet connections. If you start with the option -console and do not specify the port, you will be able to interact with the console through the standard input.

removing `-console` from the start arguments will make telnet available.
